name: http_client_http
description: package:http adapter for the http_client_contracts contract.
version: 0.1.1
homepage: https://github.com/haashem/http-client-contracts
repository: https://github.com/haashem/http-client-contracts/blob/main/packages/http_client_http

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  http: ^1.2.2
  http_client_contracts: ^0.1.0

dev_dependencies:
  http_client_contract_test: ^0.1.0
  lint: ^2.3.0
  mocktail: ^1.0.4
  test: ^1.25.8
